INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_ATTACK', 'Atacar', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_DEFENSE', 'Defensa', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_VERSUS', 'VS', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_SIGHT_RANGE', 'Corto alcance', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_RANGE', 'Alcance', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_MOVES', 'Movimientos', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_EXPERIENCE', 'Experiencia', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_RANGED_ATTACKS', 'Ataques a distancia', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_AIR_SWEEPS', 'Barridos aéreos', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_FASTER_IN', 'Mas rápido en', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_ROUGH_TERRAIN', 'Terreno [COLOR_POSITIVE_TEXT] ABRUPTO[ENDCOLOR]  (Colinas, bosques o selvas)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_OPEN_TERRAIN', 'Terreno[COLOR_POSITIVE_TEXT] ABIERTO[ENDCOLOR]  (NO Colinas, Bosques ni Selvas)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_WOUNDED_UNITS', 'Unidades heridas', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_FRIENDLY', 'Amistoso', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_NEUTRAL', 'Neutral', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_ENEMY', 'Enemigo', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_IN_TERRITORY', 'En territorio {1_num}', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_UPGRADE_COST', 'Coste de actualización', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_STRENGTH', 'Fuerza', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_CANNOT ENTER', 'No se puede entrar', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_UNTIL', 'Hasta', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_HEALING', 'Curación', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_FORTIFIED_UNITS', 'Unidades fortificadas', '', '');
/* Special Abilities */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_ADJACENT_ENEMIES', 'Para [COLOR_POSITIVE_TEXT]Unidades enemigas adyacentes[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_ADJACENT_FRIENDLY', 'Para unidades en casillas adyacentes.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_AIR_SWEEP', 'Puede hacer un barrido aéreo para eliminar las unidades interceptoras.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_AMPHIBIOUS', 'Daño completo al atacar desde el mar o a través de ríos.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_BLITZ', 'Puede [COLOR_POSITIVE_TEXT]atacar 2 veces[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_CAN_HEAL', 'Puede curar', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_CAPITAL_BONUS', 'En la [COLOR_POSITIVE_TEXT]Capital[ENDCOLOR]; La bonificacion disminuye a medida que la unidad se aleja.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_CAPTURE_SHIPS', '[COLOR_POSITIVE_TEXT]Captura[ENDCOLOR][COLOR_POSITIVE_TEXT]barcos[ENDCOLOR] enemigos derrotados.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_CARGO', 'Puede transportar [COLOR_POSITIVE_TEXT]{1_num}[ENDCOLOR] carga', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_EMBARKATION', 'Puede embarcar en [COLOR_POSITIVE_TEXT]casillas de agua[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_EVADE', 'Oportunidad de [COLOR_POSITIVE_TEXT]evadir[ENDCOLOR] intercepciones', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_EXTRA_INTERCEPTION', '+1 [COLOR_POSITIVE_TEXT]Interception[ENDCOLOR] extra por turno.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_FAST_ATTACK', 'Los ataques utilizan [COLOR_POSITIVE_TEXT]1 movimiento[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_FLAT_MOVEMENT', 'Todos los movimientos utilizan [COLOR_PLAYER_ORANGE_TEXT]1 Movimiento[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_FREE_UPGRADES', 'Actualizaciones gratuitas', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_GREAT_ADMIRAL', 'Mejora la eficacia de combate cerca de [COLOR_POSITIVE_TEXT] barcos[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_GREAT_GENERAL', 'Mejora la eficacia de combate cerca de [COLOR_POSITIVE_TEXT]unidades de tierra[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_GREAT_GENERAL_MOVEMENT', 'Los [COLOR_POSITIVE_TEXT] grandes generales[ENDCOLOR]se tendrá que mover si empieza el turno [COLOR_POSITIVE_TEXT]apilado[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_GREAT_GENERAL_RATE', 'Ratio de creación de grandes generales', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_HEAL_ON_KILL', '[COLOR_POSITIVE_TEXT]Se cura {1_num} la salud[ENDCOLOR] por matar unidades no barbaras.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_IGNORE_TERRAIN_COST', 'Ignora los costes del terreno.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_INDIRECT_FIRE', 'Puede atacar a través de [COLOR_POSITIVE_TEXT]obstáculos[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_INSTANT_HEAL', '[COLOR_POSITIVE_TEXT]Se cura {1_num} la salud[ENDCOLOR][NEWLINE][COLOR_NEGATIVE_TEXT]Pierdes[ENDCOLOR] esta oportunidad al elegir un ascenso.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_INTERCEPTION', 'Oportunidad de [COLOR_POSITIVE_TEXT] interceptar[ENDCOLOR] aeronaves.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_MARCH', 'Ataque y movimiento no impiden la curación', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_MOUNTAIN_PASS', 'Puedes cruzar [COLOR_POSITIVE_TEXT]montañas[ENDCOLOR], pero te quitara salud [COLOR_NEGATIVE_TEXT]si terminas el turno[ENDCOLOR] en la montaña.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_MOVE_IMPASSIBLE', 'Se puede mover a través de [COLOR_POSITIVE_TEXT]hielo y montañas.[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_MUST_SET_UP', 'Debes instalarla para ataque a distancia.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_NO_CITY_CAPTURE', 'No es posible capturar ciudades.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_NO_DEFENSE_BONUS', 'No tiene bonificaciones defensivas por terreno.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_NO_MELEE_ATTACK', 'No puede atacar cuerpo a cuerpo.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_NO_UNIT_ATTACK', 'No puede atacar [COLOR_NEGATIVE_TEXT]unidades[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_PARADROP', 'Puede [COLOR_POSITIVE_TEXT]lanzarse en paracaídas[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_RIVAL_TERRITORY', 'Puede entrar en [COLOR_POSITIVE_TEXT]territorio rival[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_RIVAL_TERRITORY_FAITH', '{PROMOTION_UNWELCOME_EVANGELIST_HELP}', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_STRONGER_INTERCEPTION', '[COLOR_POSITIVE_TEXT]Intercepciones[ENDCOLOR] mas potentes.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_WEAK_RANGED', 'Ataque contra [COLOR_NEGATIVE_TEXT]tierra y buques[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_WHEN_ADJACENT_FRIENDLY', 'Cuando esta [COLOR_POSITIVE_TEXT]adyacente[ENDCOLOR] a una unidad militar amistosa.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_WHEN_EMBARKED', 'Cuando esta [COLOR_POSITIVE_TEXT]embarcada[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_WHEN_FLANKING', 'Cuando esta [COLOR_POSITIVE_TEXT]flanqueando[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_WITH_GREAT_GENERAL', 'Con un [COLOR_POSITIVE_TEXT]Gran General[ENDCOLOR] en la misma casilla', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EFFECT_WITHDRAW', 'Posibilidad de retirarse de los ataques cuerpo a cuerpo', '', '');
/* Promotion Names */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_ANTI_FIGHTER', 'Bonificacion contra combatientes (50)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_ANTI_HELICOPTER', 'Bonificacion contra Helicópteros (100)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_ANTI_TANK', 'Bonificacion contra Tanques (100)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_ARCTIC_POWER', 'Poder Ártico', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_DEFENSE_PENALTY_50', 'Penalización en defensa (50)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_DEFENSE_PENALTY_50', 'Penalización en defensa (50)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_DESERT_POWER', 'Poder del desierto', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_EMBARKED_DEFENSE', 'Defensa en embarco (100)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_FOREIGN_LANDS', 'Bonifcacion por tierra extranjera (20)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_HANDICAP', 'IA Handicap', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_HANDICAP_1', 'IA Handicap I', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_HANDICAP_2', 'IA Handicap II', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_HILL_FIGHTER', 'Combatiente de colina', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_MERCENARY', 'Mercenario', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_MOUNTED_PENALTY', 'Penalización contra unidades montadas (50)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_NAVAL_PENALTY', 'Penalización al atacar barcos (50)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_NEW_UNIT', 'Nueva unidad', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_NEW_UNIT_HELP', 'Nueva unidad', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-21'), 'TXT_KEY_PROMOTION_WEAK_RANGED', 'Penalización en ataque a tierra  (50)', '', '');

UPDATE LoadedFile SET Value=1 WHERE Type='Civup_Promotions.sql';
