--· ES_ES/YieldLibrary.sql
/*  Info emergente sobre distibución de rendimientos */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_CULTURE_WONDER_BONUS', '+{1_Num}% por tener una maravilla del mundo.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_CULTURE_CITY_MOD', '+{1_Num}% por una ciudad.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_CULTURE_PLAYER_MOD', '+{1_Num}% por el imperio.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_FOOD_USAGE', '([COLOR_POSITIVE_TEXT]{1_Num}[ENDCOLOR] - [COLOR_NEGATIVE_TEXT]{2_Num}[ENDCOLOR] consumidos por ciudadanos [ICON_CITIZEN])', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_FOODMOD_PLAYER', '[NEWLINE][ICON_BULLET]{1_Num}% por el imperio.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_FOODMOD_CAPITAL', '[NEWLINE][ICON_BULLET]{1_Num}% por la capital[ICON_CAPITAL]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_FOODMOD_UNHAPPY', '[NEWLINE][ICON_BULLET][COLOR_WARNING_TEXT]{1_Num}%[ENDCOLOR] por infelicidad [ICON_HAPPINESS_4]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_FOODMOD_WLTKD', '[NEWLINE][ICON_BULLET]{1_Num}% por el “Día de amamos al rey”', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_FOOD_CONVERSION', '[NEWLINE][ICON_BULLET]+{1_Num} [ICON_PRODUCTION] por exceso de alimentos[ICON_FOOD]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_RAILROAD_CONNECTION', '[NEWLINE][ICON_BULLET]{1_Num} por conexión ferroviaria.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_UNIT_DOMAIN', '[NEWLINE][ICON_BULLET]{1_Num}% por posesión de unidades.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_UNIT_COMBAT_TYPE', '[NEWLINE][ICON_BULLET]{1_Num}% por clase de combate.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_MILITARY', '[NEWLINE][ICON_BULLET]{1_Num}% por unidades militares.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_UNIT_WITH_BUILDING', '[NEWLINE][ICON_BULLET]{1_Num}% por {2_BuildingName}', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_WONDER_CITY', '[NEWLINE][ICON_BULLET]{1_Num}% por Maravillas (Ciudad)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_WONDER_PLAYER', '[NEWLINE][ICON_BULLET]{1_Num}% por Maravillas (imperio)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_WONDER_LOCAL_RES', '[NEWLINE][ICON_BULLET]{1_Num}% por Maravillas ({2_ResourceName})', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_BUILDING_CITY', '[NEWLINE][ICON_BULLET]{1_Num}% por edificios.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_CAPITAL_BUILDING_TRAIT', '[NEWLINE][ICON_BULLET]{1_Num}% por edificios en la capital [ICON_CAPITAL] (Característica)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_SPACE', '[NEWLINE][ICON_BULLET]{1_Num}% por nave espacial (Imperio)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_UNIT_SUPPLY', '[NEWLINE][ICON_BULLET]{1_Num}% por suministros de unidades (Imperio)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_MILITARY_PLAYER', '[NEWLINE][ICON_BULLET]{1_Num}% por unidades militares (Imperio)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_SETTLER_PLAYER', '[NEWLINE][ICON_BULLET]{1_Num}% por colonos (Imperio)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_CAPITAL_SETTLER_PLAYER', '[NEWLINE][ICON_BULLET]{1_Num}% por colonos (Capital)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_RELIGION_PLAYER', '[NEWLINE][ICON_BULLET]{1_Num}% por construcciones religiosas (Imperio)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_UNIT_COBMAT_CLASS_PLAYER', '[NEWLINE][ICON_BULLET]{1_Num}% por clase de combate (Imperio)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_UNIT_TRAIT', '[NEWLINE][ICON_BULLET]{1_Num}% por tipo de unidad (Característica)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_BUILDING_TRAIT', '[NEWLINE][ICON_BULLET]{1_Num}% por edificios (Característica)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_WONDER_POLICY', '[NEWLINE][ICON_BULLET]{1_Num}% por maravillas (Política)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_BUILDING_POLICY', '[NEWLINE][ICON_BULLET]{1_Num}% por edificios (Política)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_WORLD_WONDER_PLAYER', '[NEWLINE][ICON_BULLET]{1_Num}% por Maravillas del mundo (Imperio)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_TEAM_WONDER_PLAYER', '[NEWLINE][ICON_BULLET]{1_Num}% por Maravillas del equipo (Imperio)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_NATIONAL_WONDER_PLAYER', '[NEWLINE][ICON_BULLET]{1_Num}% por Maravillas nacionales (Imperio)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_BUILDING_POLICY_PLAYER', '[NEWLINE][ICON_BULLET]{1_Num}% por edificios (Mod. Política del imperio)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_SPACE_PLAYER', '[NEWLINE][ICON_BULLET]{1_Num}% por nave espacial (Imperio)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_SPECIALIST_PLAYER', '[NEWLINE][ICON_BULLET]{1_Num}% por especialistas (Imperio)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_YIELD', '[NEWLINE][ICON_BULLET]{1_Num}% por ciudad.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_YIELD_RESOURCES', '[NEWLINE][ICON_BULLET]{1_Num}% por recursos.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_YIELD_HAPPINESS', '[NEWLINE][ICON_BULLET]{1_Num}% por felicidad.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_YIELD_AREA', '[NEWLINE][ICON_BULLET]{1_Num}% por área', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_YIELD_PLAYER', '[NEWLINE][ICON_BULLET]{1_Num}% por miscelánea.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_YIELD_CAPITAL', '[NEWLINE][ICON_BULLET]{1_Num}% por Capital [ICON_CAPITAL]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_YIELD_GOLDEN_AGE', '[NEWLINE][ICON_BULLET]{1_Num}% por edad de oro.', '', '');
/*  Misceláneos */
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_YIELD_BREAKDOWN', '[{1_color}]{2_stored}[ENDCOLOR]/[{1_color}]{3_needed}[ENDCOLOR] ([{1_color}]+{4_rate}[ENDCOLOR] por turno) {5_icon} {6_desc}', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TOPIC_LAW', 'Ley', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TOPIC_POPULATION', 'Ciudadano', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TOPIC_CS_MILITARY', 'Puntos por turno', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PER_CITY', 'Por ciudad', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_SPLIT_AMONG_CITIES', 'Dividido entre tus ciudades', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_MILITARY_UNIT_REWARDS', 'Unidad militar', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_SCIENCE_FROM_HAPPINESS', '[ICON_BULLET][COLOR_POSITIVE_TEXT]{1_Num}%[ENDCOLOR] [ICON_RESEARCH] por {1_Num} felicidad [ICON_HAPPINESS_1]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_SCIENCE_FROM_UNHAPPINESS', '[ICON_BULLET][COLOR_POSITIVE_TEXT]-{1_Num}%[ENDCOLOR] [ICON_RESEARCH] por {1_Num} infelicidad [ICON_HAPPINESS_4]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_GOLD_FOR_FREE', '{1_Num} gratis.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_GOLD_FROM_OPEN_BORDERS', '{1_Num} por acuerdo de apertura mutua de fronteras con otros lideres.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_HAPPINESS_CITYSTATES', '{1_Num} de Felicidad Nacional por ciudades-estado.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_HAPPINESS_DIFFICULTY_LEVEL', '{1_Num} de Felicidad Nacional gratuita.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_SCIENCE_FROM_RESEARCH_AGREEMENTS', '[ICON_BULLET][COLOR_POSITIVE_TEXT]{1_Num}[ENDCOLOR] [ICON_RESEARCH] por acuerdos de investigacion.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_YIELD_FROM_LUXURIES', '{1_Num} por recursos de lujo.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_GOLD_FROM_POLICIES', '{1_Num} por políticas', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_YIELD_FROM_POLICIES', '{1_Num} {2_icon} por políticas', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_YIELD_FROM_TRAITS', '{1_Num} {2_icon} por rasgos.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_YIELD_FROM_PROCESSES', '{1_Num} {2_IconString} por procesos.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_YIELD_FROM_MINOR_CIVS', '{1_num} {2_icon} por ciudades-estado.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_CITYSTATE_MODIFIER_FOCUS', '{2_icon} Foco de ciudad: {1_num}%', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_CITYSTATE_MODIFIER_POPULATION', 'Población:[ICON_CITIZEN] {1_num}', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_CITYSTATE_MODIFIER_NOT_CONNECTED', 'No conectado: [ICON_CONNECTED] {1_num}%', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_CITYSTATE_MODIFIER_IS_RAZING', 'Arrasando: [ICON_RAZING] {1_num}%', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_CITYSTATE_MODIFIER_IS_RESISTANCE', 'Resistencia: [ICON_RESISTANCE] {1_num}%', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_CITYSTATE_MODIFIER_IS_PUPPET', 'Títeres:[ICON_PUPPET] {1_num}%', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_CITYSTATE_MODIFIER_IS_OCCUPIED', 'Ocupado: [ICON_OCCUPIED]{1_num}% ', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_CITYSTATE_MODIFIER_IS_BLOCKADED', 'Bloqueado: [ICON_BLOCKADED]{1_num}%', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_CITYSTATE_MODIFIER_IS_CAPITAL', 'Capital: [ICON_CAPITAL]{1_num}%', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_CITYSTATE_MODIFIER_IS_AVOID', 'Evitar crecimiento: [ICON_MUSHROOM] {1_num}%', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_CITYSTATE_MODIFIER_IS_AVOID_MANY', 'Mas de un {1_num}% de ciudades en evitar crecimiento)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_CITYSTATE_MODIFIER_WEIGHT_TOTAL', '{1_num} (ciudad) / {2_num} (imperio)={3_num}% por {4_num}{5_icon}', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_YIELD_USAGE', '([COLOR_POSITIVE_TEXT]{1_num}[ENDCOLOR] - [COLOR_NEGATIVE_TEXT]{2_num}[ENDCOLOR] consumido)', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_YIELD_SURPLUS', '{1_num} {2_icon} Superávit', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_YIELD_FROM_OTHER_YIELDS', '({1_num} {2_icon} + {3_num} {4_icon} {5_yieldstring})', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_YIELD_SETTLER_POLICY', '[NEWLINE][ICON_BULLET]Modificador de política por Colonos: {1_num}%', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_YIELD_POLICY', '[NEWLINE][ICON_BULLET]Modificador de política: {1_Num}%', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_YIELD_BUILDINGS', '[NEWLINE][ICON_BULLET]Modificador de edificios: {1_Num}%', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_CAPITAL_BUILDING_TRAIT', '[NEWLINE][ICON_BULLET]Modificador de edificios en la capital[ICON_CAPITAL]: {1_Num}%', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_YIELD_MOD_GLOBAL_BUILDINGS', '[NEWLINE][ICON_BULLET]Edificios en otras ciudades: {1_Num}%', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_PRODMOD_YIELD_HAPPINESS', '[NEWLINE][ICON_BULLET][COLOR_WARNING_TEXT]Modificador de infelicidad: [ICON_HAPPINESS_4] {1_Num}%[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_YIELD_FOR_FREE', '[ICON_BULLET][COLOR_POSITIVE_TEXT]{1_Num}[ENDCOLOR] {2_icon} gratis.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_YIELD_FROM_CITIES', '[ICON_BULLET][COLOR_POSITIVE_TEXT]{1_Num}[ENDCOLOR] {2_icon} por ciudades.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_YIELD_FROM_POLICIES', '[ICON_BULLET][COLOR_POSITIVE_TEXT]{1_Num}[ENDCOLOR] {2_icon} por ciudades.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_YIELD_FROM_MINORS', '[ICON_BULLET][COLOR_POSITIVE_TEXT]{1_Num}[ENDCOLOR] {2_icon} por ciudades-estado.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_YIELD_FROM_HAPPINESS', '[ICON_BULLET][COLOR_POSITIVE_TEXT]{1_Num}[ENDCOLOR] {2_icon} por exceso de felicidad [ICON_HAPPINESS_1]', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_YIELD_FROM_RESEARCH_AGREEMENTS', '[ICON_BULLET][COLOR_POSITIVE_TEXT]{1_Num}[ENDCOLOR] {2_icon} por acuerdos de investigación por otros jugadores.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_TP_SCIENCE', 'Ciencia [ICON_RESEARCH] que se produce en todo el imperio para el proyecto de investigación en curso.', '', '');
INSERT INTO Civup_Language_ES_ES (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-03-23'), 'TXT_KEY_NEXT_POLICY_TURN_LABEL', '{1_Num: number #} Turno/s para la siguiente política', '', '');

UPDATE LoadedFile SET Value=1 WHERE Type='Civup_YieldLibrary.sql';
